export const enum MessageType {
  UPDATE_COVER = "UPDATE_COVER",
  UPDATE_NAME = "UPDATE_NAME",
  UPDATE_EMOJI = "UPDATE_EMOJI",
  JOIN_WORKSPACE = "JOIN",
  LEAVE_WORKSPACE = "LEAVE",
  JOINED_WORKSPACE = "JOINED",
  LEFT_WORKSPACE = "LEFT",
  CONNECTED = "CONNECTED",
}
