name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 54.255.228.223
          username: ubuntu
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          script: |
            cd ~
            rm -rf serene-v3/
            git clone https://github.com/Pritam12F/serene-v3
            cd serene-v3/
            npm i -g pnpm
            npm i -g pm2
            pnpm install
            pnpm run build

            # Check if PM2 process exists and restart or start new
            if pm2 list | grep -q "serene"; then
              pm2 restart serene
            else
              pm2 start npm --name "serene" -- start
            fi
